services:
  # Development services
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: my_project
      POSTGRES_PASSWORD: "S5Qq0njgkIiBGMoapp6GEwl-9LrAVfBz"
    volumes:
      - my_project_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    ports:
      - "8091:6379"
    command: redis-server --requirepass "c3MPQpwjuSHulNkcZDS9HJ1ZJw1FzT6H"
    environment:
      - REDIS_REPLICATION_MODE=master

  # Test services
  postgres_test:
    image: pgvector/pgvector:pg16
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: my_project_test
      POSTGRES_PASSWORD: "0_SgUBE6RNPopQ-yaVnEp-sj_rK9Z35B"
    volumes:
      - my_project_test_data:/var/lib/postgresql/data

  redis_test:
    image: redis:6.2.6
    ports:
      - "9091:6379"
    command: redis-server --requirepass "pSQQSf6ViHABi41qvLOs5PvOMx2kBD71"
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  my_project_data:
  my_project_test_data:
